steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sharp-kayak-409616/rkc-telegram-bot', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sharp-kayak-409616/rkc-telegram-bot']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'myrkcschedulebot', '--image', 'gcr.io/sharp-kayak-409616/rkc-telegram-bot', '--region', 'us-central1']
images:
- gcr.io/sharp-kayak-409616/rkc-telegram-bot