// Code generated by "stringer -type=TransitionState"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EISideStep-0]
	_ = x[CentreStep-1]
	_ = x[WingStep-2]
	_ = x[SevaStep-3]
	_ = x[ResultStep-4]
}

const _TransitionState_name = "EISideStepCentreStepWingStepSevaStepResultStep"

var _TransitionState_index = [...]uint8{0, 10, 20, 28, 36, 46}

func (i TransitionState) String() string {
	if i < 0 || i >= TransitionState(len(_TransitionState_index)-1) {
		return "TransitionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransitionState_name[_TransitionState_index[i]:_TransitionState_index[i+1]]
}
